# yaml-language-server: $schema=../../jsonschema/auth.schema.json
settings:
  strict: true
definitions:
  - mode: apiKey
    tokenLocation:
      in: header
      name: Authorization
    value:
      value: "randomsecret"
    sessionVariables:
      x-hasura-role:
        value: user
      x-hasura-user-id:
        value: "1"
  - mode: noAuth
    sessionVariables:
      x-hasura-role:
        value: anonymous
