include:
  - path: app/connector/mypostgres_promptql/compose.yaml
services:
  engine:
    build:
      context: engine
      dockerfile: Dockerfile.engine
      pull: true
    environment:
      AUTHN_CONFIG_PATH: /md/auth_config.json
      ENABLE_CORS: "true"
      ENABLE_SQL_INTERFACE: "true"
      INTROSPECTION_METADATA_FILE: /md/metadata.json
      METADATA_PATH: /md/open_dd.json
      OTLP_ENDPOINT: http://local.hasura.dev:4317
    extra_hosts:
      - local.hasura.dev:host-gateway
    labels:
      io.hasura.ddn.service-name: engine
    ports:
      - 3280:3000
