name: Unit tests

on:
  workflow_call:
  pull_request:
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY: ghcr.io
  DOCKER_IMAGE_NAME: relychan/rely-auth

permissions:
  pull-requests: write
  
jobs:
  lint:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: ./go.mod
      - name: Format
        run: diff -u <(echo -n) <(gofmt -d -s .)
      - name: Vet
        run: go vet ./...
      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
      - name: Test
        run: make test
      - name: Go coverage format
        if: ${{ github.event_name == 'pull_request' && github.repository == 'relychan/rely-auth' }}
        run: |
          go get github.com/boumenot/gocover-cobertura
          go install github.com/boumenot/gocover-cobertura
          gocover-cobertura < coverage.out > coverage.xml
      - name: Code Coverage Summary Report
        if: ${{ github.event_name == 'pull_request' && github.repository == 'relychan/rely-auth' }}
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: "50 80"
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository }}
        with:
          path: code-coverage-results.md
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2

      - name: Get version from tag
        id: get-version
        # if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        run: |
          echo "ref_version=${GITHUB_SHA:0:10}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Build image
        id: docker-build
        # if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        run: |
          docker build --build-arg VERSION=$VERSION \
            -t "$DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:$VERSION" .
        env:
          VERSION: ${{ steps.get-version.outputs.ref_version }}
          
      - name: Scan High/Critical Vulnerabilities
        uses: aquasecurity/trivy-action@0.33.1
        # if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        with:
          scan-type: "image"
          image-ref: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.get-version.outputs.ref_version }}
          format: table
          severity: "CRITICAL,HIGH"
          scanners: vuln
          ignore-unfixed: true
          exit-code: 1